---
- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: latest
    update_cache: yes
    cache_valid_time: 3600

# - name: Извлечь GPG-ключ из файла
#   apt_key:
#     data: "{{ lookup('file', '/home/max/monitoring/roles/install_grafana/files/key.txt') }}"
#     state: present
- name: add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no


- name: add repository
  apt_repository:
    repo: "deb https://dl.grafana.com/oss/release/grafana_10.2.3_amd64.deb stable main"             
    state: present
    validate_certs: no
  notify: Update apt cache

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Create grafana system group
  ansible.builtin.group:
    name: grafana
    system: true
    state: present

- name: Create grafana system user
  ansible.builtin.user:
    name: grafana
    system: true
    shell: "/usr/sbin/nologin"
    group: grafana
    createhome: false

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://192.168.1.143:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0
